adding feature of service in publish method
softonic/laravel-protobuf-events pull request #10
Opened 2023-03-14 22:24 UTC by Lotykun

With this new feature, we can isolate several services in order to avoid possible collisions with consumers with the same routing_key; This aggregates more entropy to the routing_key

2023-03-15 08:53 UTC, xaviapa approved these changes

2023-03-16 11:26 UTC, joskfg commented on src/ExternalEvents.php
> +    public static function publish(string $service, Message $class, array $headers = []): void
If the service is mandatory, the Client should it be too. If not the system is broke, because you cannot know the service to respond if there is no info about who is calling you.

2023-03-20 09:18 UTC, xaviapa requested changes

2023-03-20 09:18 UTC, xaviapa commented on config/config.php
Could we find a better name for this config?

2023-03-20 09:18 UTC, xaviapa commented on config/config.php
> +    | Ex: env('SITE', 'global') . '_' . applicationName()
This example is our case, we shouldn't expose our implementation in a public repository.

2023-03-20 09:18 UTC, xaviapa commented on src/ExternalEvents.php
> +            'client'  => config('client'),
That's a bit weird, as a standard, usually the config helpers need the config name + the key.

2023-03-20 12:48 UTC, xaviapa approved these changes

2023-03-21 11:19 UTC, joskfg commented on config/protobuf-events.php
> +    'client' => env('RABBITEVENTS_CLIENT_ID', 'laravel-protobuf-events'),
I rather null default value to avoid clients to be set to this value without knowing it.

2023-03-21 11:21 UTC, joskfg commented on src/ExternalEvents.php
> +                $eventParameter = new ReflectionParameter([$listenerClass, 'setClient'], 0);
We should keep consistency between the setClient and setHeaders check.

2023-03-21 11:22 UTC, joskfg commented on src/ServiceProvider.php
> +<?php
Remember to allow Laravel to discover this provider automatically for autoregister.

2023-03-21 17:29 UTC, joskfg commented on src/ExternalEvents.php
> +                    throw new ReflectionException();
You can modify the catch to capture two exceptions instead of force here an exception that is not real.

2023-03-21 17:30 UTC, joskfg approved these changes

2023-03-22 13:11 UTC, merged